# Generated by Django 3.2 on 2025-05-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_especialidad_ocupacion_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'verbose_name': 'Ocupacion', 'verbose_name_plural': 'Ocupaciones'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.especialidad'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='ocupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.ocupacion'),
        ),
    ]
